<?php

namespace App\Presenters;


use Nette\Application\UI\Presenter;

/**
 * Basic presenter for all other presenters
 * @package App\Presenters
 */
abstract class BasePresenter extends Presenter
{

    public function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub

        $this->setUpTimer();
    }

    public function setUpTimer()
    {

        if ($this->m_taskManager->isTracking($this->user->getId())) {
            $this->template->active = 1;

            $data = $this->m_taskManager->getTrackingTime($this->user->getId());
            $this->template->h = $data['h'];
            $this->template->m = $data['m'];
            $this->template->s = $data['s'];
        } else {
            $this->template->active = 0;
            $this->template->h = 0;
            $this->template->m = 0;
            $this->template->s = 0;
        }
    }

    protected function startup()
    {
        parent::startup();
        if (!$this->getUser()->isLoggedIn()) {
            $this->flashMessage('You must login first.');
            $this->redirect(':Track:Login:default');
        }

        $this->template->userName = $this->getUser()->getIdentity()->username;
    }
}